FROM centos:6

ADD build.sh /
RUN /build.sh

ENV GCC5_ROOT=/root/gcc5
ENV PATH=$GCC5_ROOT/bin:$PATH
ENV MANPATH=$GCC5_ROOT/share/man:MANPATH
ENV INFOPATH=$GCC5_ROOT/share/info:$INFOPATH
ENV LD_LIBRARY_PATH=$GCC5_ROOT/lib64:$GCC5_ROOT/lib:$LD_LIBRARY_PATH
ENV LD_RUN_PATH=$GCC5_ROOT/lib64:$GCC5_ROOT/lib:$LD_RUN_PATH
ENV LIBRARY_PATH=$GCC5_ROOT/lib64:$GCC5_ROOT/lib:$LIBRARY_PATH
ENV INCLUDE_PATH=$GCC5_ROOT/include:$INCLUDE_PATH
ENV CPLUS_INCLUDE_PATH=$GCC5_ROOT/include:$CPLUS_INCLUDE_PATH
ENV C_INCLUDE_PATH=$GCC5_ROOT/include:$C_INCLUDE_PATH

